function mod003End()
  MOVFINISH()
  SETSYSINVARI(0,0)
  SETSYSINVARI(1,0)
  SETSYSINVARI(2,0)
  SETSYSINVARI(3,0)
  SETSYSINVARI(4,0)
  SETSYSINVARI(5,0)
  SETSYSINVARI(6,0)
  SETSYSINVARI(7,0)
  SENDSYSOUTVARI(1,1)
  PRINT("Sianal end")
end--functionend
--Fileinfomation:
